spring:
 data:
   mongodb:
     uri: mongodb://localhost/UserServiceDB
     username: root
     password: Root@123
     database: UserServiceDB
     port: 27017
     host: localhost
server:
 port: 8082